import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import '../models/announcement.dart';

/// Service de gestion des annonces du club
class AnnouncementService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Stream de toutes les annonces (temps réel)
  Stream<List<Announcement>> getAnnouncementsStream(String clubId) {
    return _firestore
        .collection('clubs/$clubId/announcements')
        .orderBy('created_at', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => Announcement.fromFirestore(doc))
          .toList();
    });
  }

  /// Récupérer les annonces (une seule fois)
  Future<List<Announcement>> getAnnouncements(String clubId) async {
    try {
      final snapshot = await _firestore
          .collection('clubs/$clubId/announcements')
          .orderBy('created_at', descending: true)
          .get();

      final announcements = snapshot.docs
          .map((doc) => Announcement.fromFirestore(doc))
          .toList();

      debugPrint('✅ ${announcements.length} annonces chargées');
      return announcements;
    } catch (e) {
      debugPrint('❌ Erreur chargement annonces: $e');
      return [];
    }
  }

  /// Créer une nouvelle annonce (admin uniquement)
  Future<void> createAnnouncement({
    required String clubId,
    required String senderId,
    required String senderName,
    required String title,
    required String message,
    required AnnouncementType type,
  }) async {
    try {
      final announcement = Announcement(
        id: '', // Auto-generated by Firestore
        title: title,
        message: message,
        senderId: senderId,
        senderName: senderName,
        type: type,
        createdAt: DateTime.now(),
      );

      await _firestore
          .collection('clubs/$clubId/announcements')
          .add(announcement.toFirestore());

      debugPrint('✅ Annonce créée: $title');
    } catch (e) {
      debugPrint('❌ Erreur création annonce: $e');
      rethrow;
    }
  }

  /// Supprimer une annonce (admin uniquement)
  Future<void> deleteAnnouncement(String clubId, String announcementId) async {
    try {
      await _firestore
          .collection('clubs/$clubId/announcements')
          .doc(announcementId)
          .delete();

      debugPrint('✅ Annonce supprimée: $announcementId');
    } catch (e) {
      debugPrint('❌ Erreur suppression annonce: $e');
      rethrow;
    }
  }

  /// Mettre à jour une annonce (admin uniquement)
  Future<void> updateAnnouncement({
    required String clubId,
    required String announcementId,
    String? title,
    String? message,
    AnnouncementType? type,
  }) async {
    try {
      final updates = <String, dynamic>{};

      if (title != null) updates['title'] = title;
      if (message != null) updates['message'] = message;
      if (type != null) updates['type'] = type.name;

      if (updates.isEmpty) return;

      await _firestore
          .collection('clubs/$clubId/announcements')
          .doc(announcementId)
          .update(updates);

      debugPrint('✅ Annonce mise à jour: $announcementId');
    } catch (e) {
      debugPrint('❌ Erreur mise à jour annonce: $e');
      rethrow;
    }
  }
}
