import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as path;
import '../models/event_message.dart';
import '../models/poll.dart';
import '../models/session_message.dart' show MessageAttachment;

/// Service de gestion des messages liés aux événements
class EventMessageService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  /// Stream des messages d'un événement (temps réel)
  Stream<List<EventMessage>> getEventMessagesStream(
    String clubId,
    String operationId,
  ) {
    return _firestore
        .collection('clubs/$clubId/operations/$operationId/messages')
        .orderBy('created_at', descending: false)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => EventMessage.fromFirestore(doc))
          .toList();
    });
  }

  /// Récupérer les messages d'un événement (une seule fois)
  Future<List<EventMessage>> getEventMessages(
    String clubId,
    String operationId,
  ) async {
    try {
      final snapshot = await _firestore
          .collection('clubs/$clubId/operations/$operationId/messages')
          .orderBy('created_at', descending: false)
          .get();

      final messages =
          snapshot.docs.map((doc) => EventMessage.fromFirestore(doc)).toList();

      debugPrint(
          '✅ ${messages.length} messages chargés pour event $operationId');
      return messages;
    } catch (e) {
      debugPrint('❌ Erreur chargement messages: $e');
      return [];
    }
  }

  /// Envoyer un message (participant inscrit uniquement)
  Future<String> sendMessage({
    required String clubId,
    required String operationId,
    required String senderId,
    required String senderName,
    required String message,
    String? replyToId,
    ReplyPreview? replyToPreview,
    List<MessageAttachment>? attachments,
    Poll? poll,
  }) async {
    try {
      final eventMessage = EventMessage(
        id: '', // Auto-generated by Firestore
        senderId: senderId,
        senderName: senderName,
        message: message,
        createdAt: DateTime.now(),
        replyToId: replyToId,
        replyToPreview: replyToPreview,
        attachments: attachments ?? [],
        poll: poll,
      );

      final docRef = await _firestore
          .collection('clubs/$clubId/operations/$operationId/messages')
          .add(eventMessage.toFirestore());

      debugPrint('✅ Message envoyé pour event $operationId');
      return docRef.id;
    } catch (e) {
      debugPrint('❌ Erreur envoi message: $e');
      rethrow;
    }
  }

  /// Créer un ReplyPreview à partir d'un message existant
  ReplyPreview createReplyPreview(EventMessage originalMessage) {
    final preview = originalMessage.message.length > 50
        ? '${originalMessage.message.substring(0, 50)}...'
        : originalMessage.message;
    return ReplyPreview(
      senderName: originalMessage.senderName,
      messagePreview: preview,
    );
  }

  /// Upload une pièce jointe et retourner l'attachment
  Future<MessageAttachment> uploadAttachment({
    required String clubId,
    required String operationId,
    required File file,
    required String type, // 'image' ou 'pdf'
  }) async {
    final filename = path.basename(file.path);
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final storagePath =
        'clubs/$clubId/operations/$operationId/attachments/${timestamp}_$filename';

    final ref = _storage.ref().child(storagePath);
    await ref.putFile(file);

    final url = await ref.getDownloadURL();
    final fileSize = await file.length();

    debugPrint('✅ Pièce jointe uploadée: $filename');

    return MessageAttachment(
      type: type,
      url: url,
      filename: filename,
      size: fileSize,
      storagePath: storagePath,
    );
  }

  Future<void> toggleReaction({
    required String clubId,
    required String operationId,
    required String messageId,
    required String emoji,
    required String userId,
  }) async {
    final messageRef = _firestore
        .collection('clubs/$clubId/operations/$operationId/messages')
        .doc(messageId);

    await _firestore.runTransaction((transaction) async {
      final snapshot = await transaction.get(messageRef);
      if (!snapshot.exists) return;

      final message = EventMessage.fromFirestore(snapshot);
      final reactions = message.reactions.map(
        (key, value) => MapEntry(key, List<String>.from(value)),
      );
      final users = List<String>.from(reactions[emoji] ?? const []);

      if (users.contains(userId)) {
        users.remove(userId);
      } else {
        users.add(userId);
      }

      if (users.isEmpty) {
        reactions.remove(emoji);
      } else {
        reactions[emoji] = users;
      }

      transaction.update(messageRef, {'reactions': reactions});
    });
  }

  Future<void> togglePollVote({
    required String clubId,
    required String operationId,
    required String messageId,
    required String optionId,
    required String userId,
  }) async {
    final messageRef = _firestore
        .collection('clubs/$clubId/operations/$operationId/messages')
        .doc(messageId);

    await _firestore.runTransaction((transaction) async {
      final snapshot = await transaction.get(messageRef);
      if (!snapshot.exists) return;

      final message = EventMessage.fromFirestore(snapshot);
      final poll = message.poll;
      if (poll == null || poll.isClosed) return;

      final options = poll.options
          .map((option) =>
              option.copyWith(votes: List<String>.from(option.votes)))
          .toList();
      final selectedIndex =
          options.indexWhere((option) => option.id == optionId);
      if (selectedIndex == -1) return;

      final hasSelectedOption = options[selectedIndex].votes.contains(userId);

      if (!poll.allowMultiple) {
        for (var i = 0; i < options.length; i++) {
          final updatedVotes = List<String>.from(options[i].votes)
            ..remove(userId);
          options[i] = options[i].copyWith(votes: updatedVotes);
        }
        if (!hasSelectedOption) {
          final updatedVotes = List<String>.from(options[selectedIndex].votes)
            ..add(userId);
          options[selectedIndex] =
              options[selectedIndex].copyWith(votes: updatedVotes);
        }
      } else {
        final updatedVotes = List<String>.from(options[selectedIndex].votes);
        if (hasSelectedOption) {
          updatedVotes.remove(userId);
        } else {
          updatedVotes.add(userId);
        }
        options[selectedIndex] =
            options[selectedIndex].copyWith(votes: updatedVotes);
      }

      transaction.update(messageRef, {
        'poll': poll.copyWith(options: options).toMap(),
      });
    });
  }

  Future<void> closePoll({
    required String clubId,
    required String operationId,
    required String messageId,
  }) async {
    final messageRef = _firestore
        .collection('clubs/$clubId/operations/$operationId/messages')
        .doc(messageId);

    await _firestore.runTransaction((transaction) async {
      final snapshot = await transaction.get(messageRef);
      if (!snapshot.exists) return;

      final message = EventMessage.fromFirestore(snapshot);
      final poll = message.poll;
      if (poll == null || poll.isClosed) return;

      transaction.update(messageRef, {
        'poll': poll.copyWith(closedAt: DateTime.now()).toMap(),
      });
    });
  }

  /// Récupérer un message par ID
  Future<EventMessage?> getMessage({
    required String clubId,
    required String operationId,
    required String messageId,
  }) async {
    try {
      final doc = await _firestore
          .collection('clubs/$clubId/operations/$operationId/messages')
          .doc(messageId)
          .get();

      if (!doc.exists) return null;
      return EventMessage.fromFirestore(doc);
    } catch (e) {
      debugPrint('❌ Erreur récupération message: $e');
      return null;
    }
  }

  // markMessageAsRead, getUnreadCount, getUnreadCountStream verwijderd
  // → read tracking gaat nu via LocalReadTracker + UnreadCountService

  /// Vérifier si l'utilisateur est inscrit à l'événement
  Future<bool> isUserParticipant({
    required String clubId,
    required String operationId,
    required String userId,
  }) async {
    try {
      // Query by membre_id field, not by document ID
      final snapshot = await _firestore
          .collection('clubs/$clubId/operations/$operationId/inscriptions')
          .where('membre_id', isEqualTo: userId)
          .get();

      final isParticipant = snapshot.docs.isNotEmpty;
      debugPrint(
          'User $userId ${isParticipant ? "IS" : "IS NOT"} participant for event $operationId');

      return isParticipant;
    } catch (e) {
      debugPrint('❌ Erreur vérification participant: $e');
      return false;
    }
  }

  /// Supprimer un message (auteur ou admin uniquement)
  Future<void> deleteMessage({
    required String clubId,
    required String operationId,
    required String messageId,
  }) async {
    try {
      await _firestore
          .collection('clubs/$clubId/operations/$operationId/messages')
          .doc(messageId)
          .delete();

      debugPrint('✅ Message supprimé: $messageId');
    } catch (e) {
      debugPrint('❌ Erreur suppression message: $e');
      rethrow;
    }
  }

  /// Modifier un message existant (auteur uniquement).
  ///
  /// Update [message] + [attachments] + [edited_at] in Firestore. Attachments
  /// die verwijderd werden (d.w.z. in [removedAttachments]) worden daarna ook
  /// uit Firebase Storage verwijderd (best-effort — errors worden gelogd maar
  /// rethrow'en niet).
  Future<void> updateMessage({
    required String clubId,
    required String operationId,
    required String messageId,
    required String newText,
    required List<MessageAttachment> attachments,
    List<MessageAttachment> removedAttachments = const [],
  }) async {
    try {
      await _firestore
          .collection('clubs/$clubId/operations/$operationId/messages')
          .doc(messageId)
          .update({
        'message': newText,
        'attachments': attachments.map((a) => a.toMap()).toList(),
        'edited_at': Timestamp.fromDate(DateTime.now()),
      });

      // Best-effort cleanup van storage voor verwijderde attachments.
      for (final removed in removedAttachments) {
        final p = removed.storagePath;
        if (p == null || p.isEmpty) continue;
        try {
          await _storage.ref().child(p).delete();
        } catch (e) {
          debugPrint('⚠️ Kon attachment niet verwijderen uit Storage: $p ($e)');
        }
      }

      debugPrint('✅ Message bijgewerkt: $messageId');
    } catch (e) {
      debugPrint('❌ Erreur mise à jour message: $e');
      rethrow;
    }
  }

  // markMessagesAsRead verwijderd → LocalReadTracker.markAsRead('operation_$opId')
}
