// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmU-7GABqko2N-2saQNcNNSIyW_BbVCtU',
    appId: '1:328464166969:web:ee7f4452f92b1b338f5de8',
    messagingSenderId: '328464166969',
    projectId: 'calycompta',
    authDomain: 'calycompta.firebaseapp.com',
    storageBucket: 'calycompta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmU-7GABqko2N-2saQNcNNSIyW_BbVCtU',
    appId: '1:328464166969:android:d14870adcda5323a8f5de8',
    messagingSenderId: '328464166969',
    projectId: 'calycompta',
    authDomain: 'calycompta.firebaseapp.com',
    storageBucket: 'calycompta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8x4V38ICW3FE1Ox4VS8zN4vCpQbL5a8A',
    appId: '1:328464166969:ios:59423f69116580ea8f5de8',
    messagingSenderId: '328464166969',
    projectId: 'calycompta',
    authDomain: 'calycompta.firebaseapp.com',
    storageBucket: 'calycompta.firebasestorage.app',
    iosBundleId: 'be.calypsodc.calymob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmU-7GABqko2N-2saQNcNNSIyW_BbVCtU',
    appId: '1:328464166969:ios:8a0c98a21e1091ba8f5de8',
    messagingSenderId: '328464166969',
    projectId: 'calycompta',
    authDomain: 'calycompta.firebaseapp.com',
    storageBucket: 'calycompta.firebasestorage.app',
    iosBundleId: 'com.calycompta.mobile',
  );
}
